name: Integration tests for Slik.Cord

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: Set up .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Registry
      uses: docker/login-action@v1
      with:       
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push .Net 5 container     
      uses: docker/build-push-action@v2
      with:
        build-args: FRAMEWORK=5.0
        push: true
        file: src/SlikCord/Dockerfile
        tags: ghcr.io/insvald/slik-cord:5.0        
    - name: Start container
      run: docker run -d -p 3099:80 ghcr.io/insvald/slik-cord:5.0
    - name: Restore, build and test
      run: dotnet test tests/SlikCord.IntegrationTests --framework net5.0
