name: Integration tests for Slik.Cord

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        packages: write
        contents: read
    steps:
    - uses: actions/checkout@v2 
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: build .Net 5 container     
      uses: docker/build-push-action@v1
      with:
        build-args: FRAMEWORK=5.0
        file: src/SlikCord/Dockerfile
        tags: insvald/slik-cord:5.0
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: insvald/slik/slik-cord
    - name: Start containers (docker-compose)
      run: |
                    docker-compose up -d  
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test tests/SlikCord.IntegrationTests --no-build --verbosity normal
